### ISSUE TITLE
Blazor server app on PCF with websocket connection issues

### ISSUE THREAD

**Issue by jkarra2020** [analogrelay/analogrelay#1]
Hello, I am trying to deploy a Blazor server application on Pivotal cloud foundry - with Nginx reverse proxy and Kestrel web server. When I try to run on more than 1 instance, the websocket connection intermittently fails (works fine with 1 instance). I did read about the Azure SingalR service, but is not an option since we are not deploying the app to Azure. I tried out the Redis backplane, but we could not get to set the nginx with sticky session as our org does not permit that. 
I tried playing around with the HubConnection settings, specifically using websocket transport and Kestrel settings but that did not help much.
What are the other options I could try. Please help me with getting this to work.

Here is the error message I got from the Developer tools -
Websocket connection to <app link> failed: Error during webSocket handshake: unexpected response code: 404

[WebSocketsErrorHRM.txt](https://github.com/anurse/anurse/files/5123060/WebSocketsErrorHRM.txt)

**Comment by analogrelay** [comment]
I'd suggest asking a question like that on the [dotnet/aspnetcore repository](https://github.com/dotnet/aspnetcore/). I'm no longer with the ASP.NET Core team, so I don't have the latest information.
