### ISSUE TITLE
SignalR, How to define methods in the Hub class that clients can call

### ISSUE THREAD

**Issue by clw-helb** [analogrelay/analogrelay#4]
Hi anurse,
reading through  
https://docs.microsoft.com/en-us/aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-server#how-to-define-methods-in-the-hub-class-that-clients-can-call
I came along 
https://github.com/dotnet/AspNetDocs/blob/main/aspnet/signalr/overview/guide-to-the-api/hubs-api-guide-server/samples/sample23.cs?highlight=5

In order for this to work mustn’t Hub be extended with a Generic type/interface that declares “addNewMessageToPage(name, message)”? I.e.

```
public interface IMyClient
    {
        Task addNewMessageToPage(string name, string message);
    }
    public class ContosoChatHub : Hub<IMyClient>
    {
        public async Task NewContosoChatMessage(string name, string message)
        {
            await Clients.All.addNewMessageToPage(name, message);
        }
}
```

Regards
Clemens
PS: sorry for bugging you with the same issue by email ;-)

**Comment by analogrelay** [comment]
I mentioned this over email, but the docs you're referencing refer to ASP.NET 4.x SignalR. In that version, `Clients.All` was type `dynamic`, so you can call any method you want. You don't really get the advantage of strong typing, so it's not much different from how ASP.NET Core SignalR works, which uses strings (for example: `Clients.All.Invoke("addNewMessageToPage", name, message)`).

You're correct though that you _can_ define an interface and use `Hub<T>` to get strong typing. That works in **both** ASP.NET 4.x SignalR and ASP.NET Core SignalR!

One side note: I no longer work on the ASP.NET team, so if you have further issues, I suggest filing bugs through the feedback section on the docs, or going to the ASP.NET Core repo at http://github.com/dotnet/aspnetcore !

Hope that helps! 🎉
