### ISSUE TITLE
One page Razor/Blazor file

### ISSUE THREAD

**Issue by zawhtut** [analogrelay/analogrelay#5]
Hi... I've just known you via MS Dev posts... May I have a question about Razor/Blazor...?

Can I create a razor file with Razor tags and C# code and then to be transpiled into HTML and JavaScript without MVC or any other architecture?

Normally, the Blazor code flow is :
Program.cs -> Startup.cs -> _Host.cshtml -> App.razor -> MainLayout.razor -> NavMenu <-> @Page <-> @Body
This would be the whole nine yards... 

I just simply want a Something.razor file to be generated to Something.html with Something.js for a browser. 
If I want it as desktop app, maybe it could be compiled into .exe file or .app on macOS... via WebWindow or WKWebView... 🤔🤔🤔...

**Comment by analogrelay** [comment]
There are some tools like [Graze](https://github.com/mikoskinen/graze) that provide static generation of Razor content. I'm not very familiar with them though. There's no _official_ way to do it.

**Comment by zawhtut** [comment]
I see... Thanks for the tips... I am thinking of making a bare minimum Razor/Blazor... I'm still learning... I will try to take things apart from the template-created project and see what works... Thanks again... 😊...
